### ISSUE TITLE
Clarification for the record identifier

### ISSUE THREAD

**Issue by cristiroma** [scbd/scbd.github.io#1]
I am trying to setup a integration with the SCBD API. Looking at https://chm.cbd.int/api/v2013/index/select?q=realm_ss:chm+AND+schema_s:nationalReport+AND+government_s:ca&rows=1 can you please confirm  that `identifier_s` is the PK and guaranteed to be preserved across future system migrations (i.e. API v2015) and unique?

**Comment by blaisefonseca** [comment]
@cristiroma I can confirm `identifier_s` is PK and will be preserved in future migrations.
