### ISSUE TITLE
Taxonomies have English translations copied to other languages

### ISSUE THREAD

**Issue by cristiroma** [scbd/scbd.github.io#2]
I cannot find the SCBD API framework repository so I am reporting issue here. The API is exposing multilingual data, but the other languages are populated with English. This makes integration with other multilingual systems complex. Can you please fix this?

https://chm.cbd.int/api/v2013/index/select?q=realm_ss:chm+AND+schema_s:nationalReport+AND+government_s:ca&rows=1

```
"title_s": "Canada - First National Report",
"title_t": "Canada - First National Report",
"title_AR_t": "Canada - First National Report",
"title_EN_t": "Canada - First National Report",
"title_ES_t": "Canada - First National Report",
"title_FR_t": "Canada - First National Report",
"title_RU_t": "Canada - First National Report",
"title_ZH_t": "Canada - First National Report",
"reportType_s": "F27DBC9B-FF25-471B-B624-C0F73E76C8B3",
"reportType_CAR_s": "{\"symbol\":\"F27DBC9B-FF25-471B-B624-C0F73E76C8B3\",\"ar\":\"1st National Report (1992-1998)\"}",
"reportType_CEN_s": "{\"symbol\":\"F27DBC9B-FF25-471B-B624-C0F73E76C8B3\",\"en\":\"1st National Report (1992-1998)\"}",
"reportType_CES_s": "{\"symbol\":\"F27DBC9B-FF25-471B-B624-C0F73E76C8B3\",\"es\":\"1st National Report (1992-1998)\"}",
"reportType_CFR_s": "{\"symbol\":\"F27DBC9B-FF25-471B-B624-C0F73E76C8B3\",\"fr\":\"1st National Report (1992-1998)\"}",
"reportType_CRU_s": "{\"symbol\":\"F27DBC9B-FF25-471B-B624-C0F73E76C8B3\",\"ru\":\"1st National Report (1992-1998)\"}",
"reportType_CZH_s": "{\"symbol\":\"F27DBC9B-FF25-471B-B624-C0F73E76C8B3\",\"zh\":\"1st National Report (1992-1998)\"}",
"reportType_AR_t": "1st National Report (1992-1998)",
"reportType_EN_t": "1st National Report (1992-1998)",
"reportType_ES_t": "1st National Report (1992-1998)",
"reportType_FR_t": "1st National Report (1992-1998)",
"reportType_RU_t": "1st National Report (1992-1998)",
"reportType_ZH_t": "1st National Report (1992-1998)",
"reportType_AR_s": "1st National Report (1992-1998)",
"reportType_EN_s": "1st National Report (1992-1998)",
"reportType_ES_s": "1st National Report (1992-1998)",
"reportType_FR_s": "1st National Report (1992-1998)",
"reportType_RU_s": "1st National Report (1992-1998)",
"reportType_ZH_s": "1st National Report (1992-1998)",
```

**Comment by blaisefonseca** [comment]
@cristiroma  probably there is no translation available for the term `reportType`. for simplicity, when translation is not available we update the language fields with the available text in this sequence `en => fr => es => ru => ar => zh`

**Comment by cristiroma** [comment]
@blaisefonseca sorry but I failed to see the logic of copying English to other languages. Why not leave the remote system to decide to do that in case the translation is `null`?

**Comment by randyhoulahan** [comment]
@cristiroma You are referencing the index for searching above.  To the best of my knowledge you cannot index a null value.  Instead of the using the index for your integration, can you not use the source document itself?  In this case:
https://api.cbd.int/api/v2013/documents/DDFD70D7-D172-4F8E-B628-CF8F996D64F4

**Comment by sbilodeau** [comment]
@cristiroma in addition to my college @randy.houlahan and @blaisefonseca our index is nomalized with the 6 UN languages. Our goal is to prevent requesting all failover languages when we display a page in a specific language (performance an simplicity)

**Comment by cristiroma** [comment]
Thank you, I will use the document index.
